### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by abhi1693** [githubjeka/gui-rbac-yii2#1]
Demo page is not working

**Comment by githubjeka** [comment]
Demo was disabled by timeout, to free up resources. I forget restart.

**Comment by abhi1693** [comment]
I tried your demo on my local machine. I have configured the db and also have some roles and permissions in the database before hand.
I still can't see the graphical layout of the roles and permissions. Is there anything else to be configured?

**Comment by githubjeka** [comment]
https://github.com/githubjeka/gui-rbac-yii2#use-on-local No?

**Comment by abhi1693** [comment]
It isn't working

**Comment by githubjeka** [comment]
it works
![image](https://cloud.githubusercontent.com/assets/874234/5886736/896a697c-a3bf-11e4-8ddd-f287320683f7.png)

**Comment by abhi1693** [comment]
![image](https://cloud.githubusercontent.com/assets/5083532/5886820/ac6bd2b8-a3d7-11e4-89a1-116d054acb3d.png)

**Comment by githubjeka** [comment]
Please show me logs by debug panel of browser.

**Comment by abhi1693** [comment]
No logs are being generated either

**Comment by githubjeka** [comment]
Can you get me your dump of databases?

**Comment by abhi1693** [comment]
--
-- Database: `site`
--

-- --------------------------------------------------------

--
-- Table structure for table `auth_assignment`
--

CREATE TABLE IF NOT EXISTS `auth_assignment` (
  `item_name` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `user_id` int(11) NOT NULL,
  `created_at` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `auth_assignment`
--

INSERT INTO `auth_assignment` (`item_name`, `user_id`, `created_at`) VALUES
('Creator', 1, 1421951134),
('Member', 4, 1422007432),
('Team Captain', 4, 1422007450);

-- --------------------------------------------------------

--
-- Table structure for table `auth_item`
--

CREATE TABLE IF NOT EXISTS `auth_item` (
  `name` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `type` int(11) NOT NULL,
  `description` text COLLATE utf8_unicode_ci,
  `rule_name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `data` text COLLATE utf8_unicode_ci,
  `created_at` int(11) DEFAULT NULL,
  `updated_at` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `auth_item`
--

INSERT INTO `auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES
('/*', 2, NULL, NULL, NULL, 1421942560, 1421942560),
('/admin/*', 2, NULL, NULL, NULL, 1421942560, 1421942560),
('/admin/assignment/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/assignment/assign', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/assignment/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/assignment/role-search', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/assignment/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/default/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/default/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/menu/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/menu/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/menu/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/menu/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/menu/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/menu/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/permission/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/permission/assign', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/permission/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/permission/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/permission/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/permission/role-search', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/permission/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/permission/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/role/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/role/assign', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/role/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/role/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/role/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/role/role-search', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/role/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/role/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/route/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/route/assign', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/route/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/route/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/route/route-search', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/rule/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/rule/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/rule/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/rule/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/rule/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/admin/rule/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/debug/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/debug/default/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/debug/default/download-mail', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/debug/default/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/debug/default/toolbar', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/debug/default/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/gallery-page/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/gallery-page/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/gallery-page/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/gallery-page/photo', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/gallery-page/video', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/gallery-page/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/index-page/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/index-page/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/index-page/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/index-page/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/index-page/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/index-page/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/meta/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/meta/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/meta/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/meta/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/meta/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/meta/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-page/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-page/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-page/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-page/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-page/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-page/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-quotes/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-quotes/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-quotes/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-quotes/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-quotes/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-quotes/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-schedule/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-schedule/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-schedule/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-schedule/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-schedule/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-schedule/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-topics/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-topics/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-topics/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-topics/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-topics/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/navigate-topics/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/robocon-page/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/robocon-page/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/robocon-page/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/robocon-page/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/robocon-page/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/edit/robocon-page/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/gii/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/gii/default/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/gii/default/action', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/gii/default/diff', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/gii/default/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/gii/default/preview', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/gii/default/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/gridview/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/gridview/export/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/gridview/export/download', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/club-registration/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/club-registration/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/club-registration/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/club-registration/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/club-registration/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/club-registration/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/navigate-registration/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/navigate-registration/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/navigate-registration/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/navigate-registration/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/navigate-registration/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/register/navigate-registration/view', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/site/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/site/error', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/site/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/admin/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/admin/block', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/admin/confirm', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/admin/create', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/admin/delete', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/admin/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/admin/update', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/profile/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/profile/index', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/profile/show', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/recovery/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/recovery/request', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/recovery/reset', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/registration/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/registration/confirm', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/registration/connect', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/registration/register', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/registration/resend', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/security/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/security/auth', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/security/login', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/security/logout', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/settings/*', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/settings/account', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/settings/confirm', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/settings/connect', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/settings/delete', 2, NULL, NULL, NULL, 1422087566, 1422087566),
('/user/settings/disconnect', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/settings/networks', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/user/settings/profile', 2, NULL, NULL, NULL, 1421943772, 1421943772),
('/utility/*', 2, NULL, NULL, NULL, 1421949296, 1421949296),
('/utility/default/*', 2, NULL, NULL, NULL, 1421949296, 1421949296),
('/utility/default/index', 2, NULL, NULL, NULL, 1421949296, 1421949296),
('Creator', 1, 'Full Access', NULL, NULL, 1420703854, 1421067249),
('Member', 1, 'Basic', NULL, NULL, 1420728705, 1420728987),
('Team Captain', 1, 'Full Site Access', NULL, NULL, 1420717292, 1420717292);

-- --------------------------------------------------------

--
-- Table structure for table `auth_item_child`
--

CREATE TABLE IF NOT EXISTS `auth_item_child` (
  `parent` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `child` varchar(64) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `auth_item_child`
--

INSERT INTO `auth_item_child` (`parent`, `child`) VALUES
('Creator', '/*'),
('Team Captain', '/admin/assignment/*'),
('Member', '/site/*'),
('Team Captain', '/user/admin/*'),
('Member', '/user/profile/*'),
('Member', '/user/recovery/*'),
('Member', '/user/security/*'),
('Member', '/user/settings/*'),
('Team Captain', 'Member');

-- --------------------------------------------------------

--
-- Table structure for table `auth_rule`
--

CREATE TABLE IF NOT EXISTS `auth_rule` (
  `name` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `data` text COLLATE utf8_unicode_ci,
  `created_at` int(11) DEFAULT NULL,
  `updated_at` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE IF NOT EXISTS `user` (
`id` int(11) NOT NULL,
  `username` varchar(25) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password_hash` varchar(60) NOT NULL,
  `auth_key` varchar(32) NOT NULL,
  `confirmed_at` int(11) DEFAULT NULL,
  `unconfirmed_email` varchar(255) DEFAULT NULL,
  `blocked_at` int(11) DEFAULT NULL,
  `registration_ip` varchar(255) DEFAULT NULL,
  `created_at` int(11) NOT NULL,
  `updated_at` int(11) NOT NULL,
  `flags` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `username`, `email`, `password_hash`, `auth_key`, `confirmed_at`, `unconfirmed_email`, `blocked_at`, `registration_ip`, `created_at`, `updated_at`, `flags`) VALUES
(1, 'abhimanyu', 'abhimanyu@teamvulcans.com', '$2y$10$edAsXywgWK1L86r0iZCzVOsDNb/8tAiNFrOubhI/j4IJ3X87tt7Xm', 'lP9RNHj-q2aOXnK2KdLlo0AR8Q-mZayD', 1420702827, NULL, NULL, '127.0.0.1', 1420702827, 1420702827, 0),
(4, 'test', 'info@teamvulcans.com', '$2y$10$Mes5mBpWCom5n.Zo0yWlyOJQWMkHi5GJEiEa0P3FvEC.QW4nHMTES', 'bdFguP22cWxXXmsREsQIS_Yy2lc-2CBf', 1422007432, NULL, NULL, '127.0.0.1', 1422007432, 1422010922, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `auth_assignment`
--
ALTER TABLE `auth_assignment`
 ADD PRIMARY KEY (`item_name`,`user_id`), ADD KEY `user_id` (`user_id`);

--
-- Indexes for table `auth_item`
--
ALTER TABLE `auth_item`
 ADD PRIMARY KEY (`name`), ADD KEY `rule_name` (`rule_name`), ADD KEY `idx-auth_item-type` (`type`);

--
-- Indexes for table `auth_item_child`
--
ALTER TABLE `auth_item_child`
 ADD PRIMARY KEY (`parent`,`child`), ADD KEY `child` (`child`);

--
-- Indexes for table `auth_rule`
--
ALTER TABLE `auth_rule`
 ADD PRIMARY KEY (`name`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `user_unique_username` (`username`), ADD UNIQUE KEY `user_unique_email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=5;
--
-- Constraints for dumped tables
--

--
-- Constraints for table `auth_assignment`
--
ALTER TABLE `auth_assignment`
ADD CONSTRAINT `auth_assignment_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT `auth_assignment_ibfk_2` FOREIGN KEY (`item_name`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `auth_item`
--
ALTER TABLE `auth_item`
ADD CONSTRAINT `auth_item_ibfk_1` FOREIGN KEY (`rule_name`) REFERENCES `auth_rule` (`name`) ON DELETE SET NULL ON UPDATE CASCADE;

--
-- Constraints for table `auth_item_child`
--
ALTER TABLE `auth_item_child`
ADD CONSTRAINT `auth_item_child_ibfk_1` FOREIGN KEY (`parent`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT `auth_item_child_ibfk_2` FOREIGN KEY (`child`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE;

**Comment by githubjeka** [comment]
![image](https://cloud.githubusercontent.com/assets/874234/5887005/643fdb58-a3cb-11e4-93f5-0c7fe432c9ca.png)

I will fix it

**Comment by sadovnik** [comment]
Seems like the demo is not available again.

**Comment by githubjeka** [comment]
Thanks.
This is public project on c9.io. 
You can rerun it in https://ide.c9.io/githubjeka/basic-rbac probably. Restarted again. Fall off a day probably :)

**Comment by githubjeka** [comment]
@abhi1693 I fixed white screen. 
![image](https://cloud.githubusercontent.com/assets/874234/6968336/a3f68282-d96e-11e4-81c6-7712bbe51f0c.png)

**Comment by sadovnik** [comment]
Thanks!

**Comment by wakjoko** [comment]
Seems like the demo is not available again.

**Comment by githubjeka** [comment]
@wakjoko works now. Again :)
