### ISSUE TITLE
With d3 v4.2.2 not working

### ISSUE THREAD

**Issue by kullarkert** [githubjeka/gui-rbac-yii2#10]
When using latest d3.js I get javascript error

app.js:9 Uncaught TypeError: d3.xhr is not a function

**Comment by githubjeka** [comment]
Thanks. I will fix it.

**Comment by kullarkert** [comment]
I tried to fix myself, but turned out there are so many changes that need to apply and logic has changed. Maybe you add rule to composer.json, that d3.js must be under version 4 and make release and when you have fixed then you could make another release that d3.js must be version 4?

**Comment by githubjeka** [comment]
Done, try.

**Comment by kullarkert** [comment]
Thank you. It's working fine :)
