### ISSUE TITLE
Cannot create new roles or permissions

### ISSUE THREAD

**Issue by deadmantfa** [githubjeka/gui-rbac-yii2#12]
Cannot create new permissions or roles using the crud, there is an error in the ItemController line 84

isset($_POST['ItemForm']['oldName']) is always true as its a string maybe an additional check of && $_POST['ItemForm']['oldName']!=='' would help cause it worked for me after that

**Comment by githubjeka** [comment]
Do you use master version?

**Comment by githubjeka** [comment]
Before create a new item and push SAVE button please try to push RESET FORM button.

**Comment by deadmantfa** [comment]
yes i do have the master version and I have reset the form, in both cases I got the error

**Comment by githubjeka** [comment]
Please try to use stable version 

```
"githubjeka/yii2-gui-rbac": "1.0.2"
```

**Comment by deadmantfa** [comment]
sure will try this and get back to you....

**Comment by deadmantfa** [comment]
its working thank you.... btw this is just awesome thank you for creating this and sharing with us. Also update your README.md

**Comment by githubjeka** [comment]
Done. Thanks.
