### ISSUE TITLE
create role has a problem

### ISSUE THREAD

**Issue by hanie-hadadi** [githubjeka/gui-rbac-yii2#16]
when I'm trying to save a role I get internal server error 
`xception 'yii\base\ErrorException' with message 'Call to undefined method githubjeka\rbac\models\ItemForm::getDb()'`

Yii Version ===>2.0.15.1
PHP Version ==>5.6.24

**Comment by ffurbo** [comment]
The reason is ItemForm use custom validation rule "unique", but the name is the same as built-in validation rule.
The simplest solution is to change the name of the function and update rules with new name.
