### ISSUE TITLE
Guide to enable Forms Layout?

### ISSUE THREAD

**Issue by saada** [githubjeka/gui-rbac-yii2#3]
On the README there's a Forms Layout screenshot but no instructions on setting that up.
Thank you!

**Comment by githubjeka** [comment]
This just concept, and it doesn't implemented.

> It's OK for basic hierarchy with two levels of nesting. When it's getting a bit more complex UI won't be able to efficiently visualize current state of the hierarchy. (c) samdark

I have only html sketch, if you need.
