### ISSUE TITLE
Rbac test error

### ISSUE THREAD

**Issue by dbd5** [githubjeka/gui-rbac-yii2#4]
Hello,

I am getting this "Call to a member function getRules() on a non-object" when I go to http://admin.app.dev/rbac

Please have a look at my screen and advice what I could be doing wrong, I believe I have followed the instructions you provided.

Regards,

Adam

![screen shot 2015-05-07 at 10 02 24 pm](https://cloud.githubusercontent.com/assets/9496750/7525860/def101a8-f504-11e4-890f-977904005b6e.png)

**Comment by githubjeka** [comment]
Hello, you not connected authManager.

 I think it is logical, if you are using RBAC :hatched_chick:

**Comment by dbd5** [comment]
Thanks - my fault, I've taken care of that, now the form is open but it doesn't save. This is the procedure I've followed;
1. Type in Role
2. Type in Description
3. Click save button

Any suggestion what could be wrong?

The structure of the RBAC tables are standard but its possible other extensions have modified the User table. Currently it is;

CREATE TABLE `user` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(25) NOT NULL COLLATE 'utf8_unicode_ci',
    `email` VARCHAR(255) NOT NULL COLLATE 'utf8_unicode_ci',
    `password_hash` VARCHAR(60) NOT NULL COLLATE 'utf8_unicode_ci',
    `auth_key` VARCHAR(32) NOT NULL COLLATE 'utf8_unicode_ci',
    `confirmed_at` INT(11) NULL DEFAULT NULL,
    `unconfirmed_email` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `blocked_at` INT(11) NULL DEFAULT NULL,
    `registration_ip` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `created_at` INT(11) NOT NULL,
    `updated_at` INT(11) NOT NULL,
    `status` SMALLINT(6) NOT NULL DEFAULT '10',
    `flags` INT(11) NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `user_unique_username` (`username`),
    UNIQUE INDEX `user_unique_email` (`email`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;

Regards,

Adam

**Comment by githubjeka** [comment]
Table `user` doesn't participate. 

Can you show `authManager` config ?

**Comment by dbd5** [comment]
Sure, here's a section of my /common/config/main.php;
authManager is at the very end

![screen shot 2015-05-08 at 11 17 01 am](https://cloud.githubusercontent.com/assets/9496750/7534599/efa7b752-f573-11e4-8744-108bcf806bd2.png)

**Comment by githubjeka** [comment]
Can you show result of `<?= get_class(Yii::$app->authManager); ?>`

**Comment by dbd5** [comment]
Sure, it returns the string "yii\rbac\DbManager ", screen shots below;

![screen shot 2015-05-08 at 12 39 14 pm](https://cloud.githubusercontent.com/assets/9496750/7535696/a90d9b84-f57f-11e4-9f74-6cf4e090d7fa.png)

![screen shot 2015-05-08 at 12 39 39 pm](https://cloud.githubusercontent.com/assets/9496750/7535699/c484844a-f57f-11e4-8259-1767b8f674a4.png)

**Comment by githubjeka** [comment]
And `<?= method_exists(Yii::$app->authManager, 'getRules') ?>` ? :)

**Comment by githubjeka** [comment]
Show me logs from debug tools when you clicked `save` in browser

**Comment by dbd5** [comment]
returns 1

![screen shot 2015-05-08 at 12 50 05 pm](https://cloud.githubusercontent.com/assets/9496750/7535798/f7c5946a-f580-11e4-98d7-2b2f2648dd4c.png)

**Comment by githubjeka** [comment]
Name of Role is should be typed

**Comment by dbd5** [comment]
Screen

![screen shot 2015-05-08 at 12 57 20 pm](https://cloud.githubusercontent.com/assets/9496750/7535886/df790bf2-f581-11e4-83f6-c326d56ce74a.png)

Logs;

![screen shot 2015-05-08 at 12 56 01 pm](https://cloud.githubusercontent.com/assets/9496750/7535889/edb59154-f581-11e4-8cb4-a041ed0ae520.png)

**Comment by githubjeka** [comment]
Has errors in console browser?

**Comment by dbd5** [comment]
Not really, I don't see any errors at all.
I'm totally surprised -- nothing happens when I click save.

But there's an error when I inspect element, The form is "A form to create-update-delete roles and permissions", see screenshot below;

![screen shot 2015-05-08 at 1 45 17 pm](https://cloud.githubusercontent.com/assets/9496750/7536563/da6b6d24-f588-11e4-94d6-bb00437a9aa9.png)

**Comment by githubjeka** [comment]
Need more information about this error. Line? File?

**Comment by dbd5** [comment]
Oh, it's no special file.

When you asked if there were errors on the console or browser, I did the following:
- go to url /index.php?r=rbac
- click on save button
- right click and select inspect element

Then I saw that error.

Its the standard extension files. I have made no changes at all

**Comment by githubjeka** [comment]
Here it does not appear. https://basic-rbac-githubjeka.c9.io/basic/web/index.php?r=rbac

Need the name of the file where the error occurs.

![image](https://cloud.githubusercontent.com/assets/874234/7549906/f2e829b6-f653-11e4-9533-320747847d90.png)

**Comment by dbd5** [comment]
App.js - see screenshot below
![screen shot 2015-05-09 at 3 11 26 pm](https://cloud.githubusercontent.com/assets/9496750/7550544/df5a7c78-f65d-11e4-82be-db893196f11c.png)

**Comment by githubjeka** [comment]
Please, open your rbac-gui page and enter `json` in console. You should get.
![image](https://cloud.githubusercontent.com/assets/874234/7550702/8d85fb04-f674-11e4-963f-7d0a9a1c5cd8.png)

P.S Do you work in Safari browser?

**Comment by githubjeka** [comment]
JSON.parse throws a SyntaxError exception if the string to parse is not valid JSON. 
Please check what return from `/index.php?r=rbac/default/items` url. Perhaps you have an php error .

**Comment by dbd5** [comment]
The output is {"nodes":[],"links":[]}

**Comment by githubjeka** [comment]
Ok. 

Add `'enableCsrfValidation'=>false,` to your global config:

``` php
//...
'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => '6oLSyFbXRvg8',
            'enableCsrfValidation'=>false,
        ],
//...
```

And run in console :

``` bash
curl --data "ItemForm%5Btype%5D=1&ItemForm%5BoldName%5D=&ItemForm%5Bname%5D=Users&ItemForm%5Bdescription%5D=Registered+users&ItemForm%5BruleName%5D=&ItemForm%5Bdata%5D=" https://YOUR_HOST/index.php?r=rbac/default/save-item

# should get {"oldName":"","name":"Users","type":"1","description":"Registered users","ruleName":null,"data":null}
```

Reload rbac-gui page and you should see your Role `Users`

**Comment by dbd5** [comment]
I've made the changes to the global config but I'm not sure how to run the curl command, it's a DLL. I'm using Windows/XAMPP environment.

Regarding, "Reload rbac-gui page and you should see your Role Users"

It appears you are not clear with my situation, let me recap;
- I've installed kartik-v/yii2-app-practical-a template with composer
- I've added the "dektrium/yii2-user": "0.9.*@dev" extension for login/logout user access
- I'm trying now to setup "githubjeka/gui-rbac-yii2" for RBAC
- There's only 1 user in the system but I can add more of course

The definition of the problem is that I cannot add Roles to the system even though everything seems normal, I ran into this issue at the point where I want to add Roles etc

Thanks for your support and patience in this matter

**Comment by githubjeka** [comment]
When you click  `Save` that sent POST data to `index.php?r=rbac/default/save-item` and returned model as string(json format).  If you have JSON.parse SyntaxError exception then the string to parse is not valid JSON. Respectively you have php error instead model.

In my last commnet, I want you post data to `index.php?r=rbac/default/save-item` and show me the error.

**Comment by dbd5** [comment]
Hi Evgeniy,

I guess we can close this if it can't be independently verified

Adam
