### ISSUE TITLE
Help me please!!

### ISSUE THREAD

**Issue by pitux** [githubjeka/gui-rbac-yii2#5]
Hello! I'm new on this, and i want to start the module, i have added 
'authManager' => [
              'class' => 'yii\rbac\DbManager',
        ],
in my /common/config/main-local.php, now i need to find the file called config.php to continue, can you help me? Thanks, regards.

**Comment by githubjeka** [comment]
```
'authManager' => [
'class' => 'yii\rbac\DbManager',
],
```

should be in `common/config/main.php`

**Comment by githubjeka** [comment]
README was updated
