### ISSUE TITLE
Is there some layouts file missing?

### ISSUE THREAD

**Issue by aiddroid** [githubjeka/gui-rbac-yii2#7]
Is there some layouts file missing?How can I change to form layout?!

**Comment by githubjeka** [comment]
If you mean concepts from `Readme.md` then It's just concept which I tried to used. But after discusion in https://github.com/yiisoft/yii2/issues/42 It was deleted and I stopped to using at [my-algorithms-graphs](https://github.com/githubjeka/gui-rbac-yii2#my-algorithms-graphs)

**Comment by aiddroid** [comment]
yes,RBAC-GUI is really a difficult work.
